project:
  type: website
  output-dir: docs

lang: es

website:
  title: "Revista Némesis"
  favicon: images/circle_logo_black.png
  open-graph: true
  twitter-card: true
  site-url: "https://revistanemesis.netlify.app"  
  navbar:
    title: "Revista Némesis"
    search: true
    left:
      - text: "Somos"
        menu:
          - proyecto.qmd
          - organizacion.qmd
          - text: Equipo
            href: equipo.qmd
      - text: Convocatoria XXI
        href: convocatoria.qmd
      - text: Normas para Autores
        href: normas_autores.qmd
      - text: "Publicaciones"
        menu:
          - product/columnas.qmd
          - product/comentarios.qmd
          - product/entrevistas.qmd
      
    right:
      - text: Portal Revista princial
        href: https://revistanemesis.uchile.cl
        target: _blank
      - icon: instagram
        href: https://www.instagram.com/revistanemesis
        target: _blank
      - icon: mailbox
        href: mailto:nemesis@uchile.cl
    logo: images/circle_logo_black.png
    background: "#330033"
    foreground: "#FFFFBC"
    border: true
    pinned: true
    back-to-top-navigation: false

  page-footer:
    center: "Revista Némesis - Facultad de Ciencias Sociales - Universidad de Chile © 2026"
      
format:
  html:
    theme: journal
    mainfont: "Merriweather"
    sansfont: "Source Sans Pro"
    fontsize: 1.1rem
    fontcolor: "#330033"
    linkcolor: "#009B86"
    monofont: "Fira Code"
    css: styles.css
    toc: true
    highlight-style: monokai
    title-block-banner: "#330033"
    title-block-banner-color: "#FFFFBC"

editor: source

execute:
  freeze: auto

