project:
  type: website
  output-dir: docs

website:

  favicon: images/circle_logo_black.png
  
  navbar:
    search: false
    left:
      - text: "Somos"
        menu:
          - proyecto.qmd
          - organizacion.qmd
      - text: Equipo
        href: equipo.qmd
      - text: Convocatoria XXI
        href: convocatoria.qmd
        
    right:
      - icon: instagram
        href: https://www.instagram.com/revistanemesis
        target: _blank
      - icon: twitter
        href: https://twitter.com/RevistaNemesis
        target: _blank
      - icon: facebook
        href: https://web.facebook.com/profile.php?id=100064994021305
        target: _blank
      - icon: mailbox
        href: mailto:nemesis@uchile.cl
    logo: images/circle_logo_black.png
    background: "#330033"
    foreground: "#FFFFBC"
    border: true
    pinned: true
    back-to-top-navigation: false
    
  sidebar:
      search: false
      pinned: true
      style: "docked"
      background: "light"
      foreground: "dark"
      border: true
      contents:
        - section: "Publicaciones"
          contents: 
            - text: Portal Revista princial
              href: https://revistanemesis.uchile.cl
              target: _blank
            - product/comentarios.qmd
            - product/entrevistas.qmd
            - product/columnas.qmd
            - tematica.qmd
        - section: "Alianzas"
          contents:
            - text: Teoría Social Hoy
              href: https://teoriasocialhoy.org
              target: _blank
            - text: REDES
              href: https://www.instagram.com/redes.ch
              target: _blank
      

  page-footer:
    center: "Licencias reservadas por Némesis UChile"
      
format:
  html:
    theme: journal
    mainfont: arapey
    fontsize: 1.1rem
    fontcolor: "#330033"
    linkcolor: "#009B86"
    monofont: lato
    css: styles.css
    toc: true
    highlight-style: monokai

editor: visual

execute:
  freeze: auto

